### ISSUE TITLE
Contacting you 

### ISSUE THREAD

**Issue by taboca** [TumAro/FER-Pytorch#1]
Hi Tumin, 

I am Marcio Galli - also a writer at Hackernoon, trying to make a start-up to use assistive conversational flows but in a different field. Would you like to help me understand what conversational systems can do? I see how passionate you are in this field. You can close this bug if you want. 

I also have an idea for how you can prototype your smart AI systems without using hardware. I wished to just talk for example for 1h with you with general ideas, to show my start-up idea, and more. 

MG

**Comment by TumAro** [comment]
> Hi Tumin,
> 
> I am Marcio Galli - also a writer at Hackernoon, trying to make a start-up to use assistive conversational flows but in a different field. Would you like to help me understand what conversational systems can do? I see how passionate you are in this field. You can close this bug if you want.
> 
> I also have an idea for how you can prototype your smart AI systems without using hardware. I wished to just talk for example for 1h with you with general ideas, to show my start-up idea, and more.
> 
> MG

You can connect with me at tuminspersonal@gmail.com
